#!/usr/bin/env bash
# configure nginx in such a way that its HTTP response contains a custom header

sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
sudo chmod -R "$USER":"$USER" /var/www/html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/g" /etc/nginx/nginx.conf
sudo sed -i "s/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/topsideboss2 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/g" /etc/nginx/sites-available/default

sudo service nginx restart

