#!/usr/bin/env bash
# This script installs HAproxy load balancer and configures it on a loadbalancer

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5

sudo apt-get -y update
sudo apt-get -y install haproxy=2.5.\*

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg

echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 47187-web-01 54.146.90.96:80 check\n\tserver 47187-web-02 34.207.237.23:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
