#!/usr/bin/env bash
# A script that displays a list of concurrently running processes 
# for all users, including those which might not have a TTY and 
# display in a user oriented format and shows hierarchy

ps -auxf
