#!/usr/bin/env bash
# A  Bash script that displays numbers from 1 to 100: multiples of 3 and 5 = FizzBuzz, multiple of 3 = Fizz and multiple of 5 = Buzz

i=1
while (( i <= 100 ))
do
  
  if (( i % 5 == 0 )) && (( i % 3 == 0 )); then
    echo "FizzBuzz"

  elif (( i % 5 == 0 )); then
    echo "Buzz"
  
  elif (( i % 3 == 0 )); then
    echo "Fizz"
  
  else
    echo $i
  fi
  ((i++))
done
