#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes: hours = 0 to 12 and minutes = 1 to 59

i=0

while (( i <= 12 ))
do
  echo "Hour: $i"
    j=1
    while (( j <= 59 ))
    do
      echo $j
      ((j++))
    done
  ((i++))
done
