#!/usr/bin/env bash
# A script that configures an Ubuntu server with:
# -localhost resolvves to 127.0.0.2
# -facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
